sudo: false

language: php

branches:
  except:
    - /^release-\d+\.\d+\.\d+.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - SITE_URL: https://zendframework.github.io/zend-dom
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/zendframework/zend-dom.git
    - secure: "s5/0nwMgJT6tDIAdPNbQhre95SCbs3LZf6o6rj4aX39LWyBCWFwI2VuRoh+2NQdhmAiwtE5YNmXeuL27MAQHCy6vfQkkE4cNmQa/vFwBr+ewUKjjCRrdAPoymq6D6G4Txk3Mu45juWb/O6fXZjWWUPMSwfC9CZX+J4rZzvQS3tnOyKk79gHf3P36dZwvzUe7XDcM98SFQIVCl8CXrNX5aQFcfDozaC+6k+hw4J5cyHKMBKVD0cb4cCKwmiLn9htJU8xOeL5DM9L4+zXroM3fmNpDPS3iXjhqgkAHU2c9zmJsf6pl0GLERYXpo8nd3Y/I9D5BCf7Qs5EgypEqJi41WhZ7OKZL7bBgIMP9hNQo5KTfc1Myu6JRzh4E8MwCSV5glMeEbEoX3SGtDcYfORxl2I8lSD5dRo/5E28SieKAVoZrkWHAtXJtRrx7vVOZ7hYvYUo53N7iTdY/7vzBewrbjTdzVUaHe+/S9OIFiLrAoYmlOGdX4b+q6Wly1m4P9i8CVHqDoVgVRA7F/qx3g0EK97HAI6wgiiMPPwWqZFRsGbXmaUHk4Fc/wkwuCjHWpw+2V3H8MTU0nQoU7ew5AFKKvm0d8erINoApGJziLYprcX79G1VzlHPWeCI3qi8j3r/5HQy5amEMCgUy9gyuFkFG/IAx/k9K36TmIjEtvudzt2o="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 7
    - php: hhvm 
  allow_failures:
    - php: 7
    - php: hhvm

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
